---
- name: setting up apache service
  template:
    src: templates/index.j2
    dest: /var/www/html/index.html
- name: allow http traffic
  firewalld:
    service: http
    permanent: true
    state: enabled
- name: apache service reloaded
  service:
    name: firewalld
    state: reloaded

